services:
  users-microservice:
    build:
      context: ./users-microservice/users-microservice
      dockerfile: Dockerfile
    container_name: users-microservice
    ports:
      - "8080:8080"
    depends_on:
      - postgres-users
      - rabbitmq
    networks:
      - app-network
      
  postgres-users:
    image: postgres:latest
    container_name: postgres_users
    volumes:
      - /users-microservice/data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    networks:
      - app-network
        
  postgres-orders:
    image: postgres:latest
    container_name: postgres_orders
    volumes:
      - /orders-microservice/data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5433:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - /users-microservice/data:/var/lib/rabbitmq
      - /users-microservice/data:/var/log/rabbitmq
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge